apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: my-python-app:latest  # Replace with your actual Docker image name and tag
          ports:
            - containerPort: 5000  # Port on which your application inside the container is listening
